# remote_theme: codeasashu/hcz-jekyll-blog
title: Zdeněk Kasner

description: Zdeněk Kasner - Personal website
author: Zdeněk Kasner
logo: /static/img/avatar.jpg
github: https://github.com/kasnerz
about: NLP PhD Student

baseurl: ""
url: ""

allowsearch: false

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
