# remote_theme: codeasashu/hcz-jekyll-blog
title: Zdeněk Kasner

description: Zdeněk Kasner - Personal Website
author: Zdeněk Kasner
logo: /static/img/avatar.jpg
github: https://github.com/kasnerz
about: PhD Student

baseurl: ""
url: ""

allowsearch: false

# disqus_shortname: aboutashu
# google_analytics: UA-72862926-1

# share:
#   twitter_username: \#zdenek.kasner
#   fb_appid: zdenek.kasner


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
